---
# Specify files or folders which are to be copied
files:
  # Dotfiles
  - src: files/dotfiles/.bash_profile
    dest: ~/.bash_profile
  - src: files/dotfiles/.gitconfig
    dest: ~/.gitconfig
  - src: files/dotfiles/.config/fish/config.fish
    dest: ~/.config/fish/config.fish
  - src: files/dotfiles/.ipython/profile_default/ipython_config.py
    dest: ~/.ipython/profile_default/ipython_config.py

  # DMG Audio EQuilibrium
  - src: files/dmgaudio/Default Bank.eqi
    dest: ~/Library/Application Support/DMGAudio/EQuilibrium/Default Bank.eqi

  # Software Licenses
  - src: "{{ cloud_app_license_dir }}/1Password/License.onepassword-license"
    dest: ~/Library/Group Containers/2BUA8C4S2C.com.agilebits/License/License.onepassword-license
  - src: "{{ cloud_app_license_dir }}/CanOpener/Interface.interface"
    dest: ~/Music/.GDHZ/Interface.interface
  - src: "{{ cloud_app_license_dir }}/DaisyDisk/License.DaisyDisk"
    dest: ~/Library/Application Support/DaisyDisk/License.DaisyDisk
  - src: "{{ cloud_app_license_dir }}/Dash/license.dash-license"
    dest: ~/Library/Application Support/Dash/License/license.dash-license
  - src: "{{ cloud_app_license_dir }}/Dualism/license"
    dest: ~/Library/Application Support/DMGAudio/Dualism/license
  - src: "{{ cloud_app_license_dir }}/Entropy/.els-A4AD28617A455C07768787313A53E2F79D9FA258"
    dest: ~/Library/Application Support/.els-A4AD28617A455C07768787313A53E2F79D9FA258
  - src: "{{ cloud_app_license_dir }}/EQuilibrium/license"
    dest: ~/Library/Application Support/DMGAudio/EQuilibrium/license
  - src: "{{ cloud_app_license_dir }}/Sublime Text/License.sublime_license"
    dest: ~/Library/Application Support/Sublime Text 3/Local/License.sublime_license
  - src: "{{ cloud_app_license_dir }}/Textual/Textual_User_License.plist"
    dest: ~/Library/Application Support/Textual/Textual_User_License.plist
  - src: "{{ cloud_app_license_dir }}/ValhallaVintageVerb/ValhallaVintageVerb.settings"
    dest: ~/Library/Preferences/ValhallaVintageVerb.settings
  - src: "{{ cloud_app_license_dir }}/VMware Fusion/license-fusion-80-e3-201505"
    dest: /Library/Preferences/VMware Fusion/license-fusion-80-e3-201505

# Specify files which are to be symlinked to others
symbolic_links:
  # Audio Hijack cloud storage
  - src: "{{ cloud_app_config_dir }}/Audio Hijack"
    dest: '~/Library/Application Support/Audio Hijack'
  # OpenEmu cloud storage
  - src: "{{ cloud_app_config_dir }}/OpenEmu/BIOS"
    dest: '~/Library/Application Support/OpenEmu/BIOS'
  - src: "{{ cloud_app_config_dir }}/OpenEmu/Bindings"
    dest: '~/Library/Application Support/OpenEmu/Bindings'
  - src: "{{ cloud_app_config_dir }}/OpenEmu/Cores"
    dest: '~/Library/Application Support/OpenEmu/Cores'
  - src: "{{ cloud_app_config_dir }}/OpenEmu/Game Library"
    dest: '~/Library/Application Support/OpenEmu/Game Library'
  - src: "{{ cloud_app_config_dir }}/OpenEmu/Save States"
    dest: '~/Library/Application Support/OpenEmu/Save States'
